# Use a imagem oficial do .NET 8.0 SDK
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY . .

# Restaura as dependências
RUN dotnet restore

# Executa os testes
ENTRYPOINT ["dotnet", "test", "--filter", "FullyQualifiedName~MonitoramentoAmbiental.Tests.Features.GerenciamentoDeAlertasClimaticosFeature"] 