// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoramentoAmbiental.Data.Contexts;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MonitoramentoAmbiental.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241206090515_FixAlertasIndex")]
    partial class FixAlertasIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoramentoAmbiental.Models.AlertaModel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ALTERADO_EM");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("VARCHAR2(127 BYTE)")
                        .HasColumnName("CATEGORIA");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CRIADO_EM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_INICIO");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DELETADO_EM");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("VARCHAR2(1024 BYTE)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255 BYTE)")
                        .HasColumnName("LOCALIDADE");

                    b.Property<DateTime>("PrevisaoTermino")
                        .HasColumnType("DATE")
                        .HasColumnName("PREVISAO_TERMINO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255 BYTE)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.ToTable("TBL_ALERTAS_CLIMATICOS", (string)null);
                });

            modelBuilder.Entity("MonitoramentoAmbiental.Models.UsuarioModel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ALTERADO_EM");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CRIADO_EM");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DELETADO_EM");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NOME");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SENHA_HASH");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TBL_USUARIOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
